Sprint 1/step 2
Fighter9021/React-burger pull request #1
Opened 2022-11-05 03:30 UTC by Fighter9021

2022-11-05 06:18 UTC, ArslanDev666 commented on src/components/app-header/app-header.jsx
> +                </span>
**Надо исправить**

Оберните иконку и текст в ссылку в шапке в ссылку `<a href="#">`

Например
```js
<a href="#" class="......">
   <BurgerIcon type="primary" /> Конструктор
</a>
```
В следующих спринтах вместо ссылки будет компонент Link из библиотеки react router, а пока сделайте просто ссылкой

2022-11-05 06:47 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа.
Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;
- Реализован функционал компонента Popup с помощью Portals;
- Реализован контент в компоненте Popup через children;

### **Но есть несколько замечаний, которые нужно исправить:**

- Еще раз сверьте вёрстку с макетом.

  У ваших блоков слишком маленькая высота: https://yadi.sk/d/GJN1TNoreQfltQ;
  В макете она намного больше: https://yadi.sk/d/UpLo_a-Wgw3KmQ;

- Поправьте вёрстку модального окна с заказом.

  Как у вас: https://yadi.sk/d/cdyoAtSEeYGTfw;
  Как в макете: https://yadi.sk/d/OH0ssw77ccf4XQ;

- По нажатию на ингредиент (даже на картинку) должно открываться модальное окно, с деталями об этом ингредиенте. У вас же ингредиент добавляется в burgerConstructor. На данном этапе вам не нужен этот функционал, поэтому рекомендую убрать его.

- В макете цена у ингредиентов расположена по середине;

- Исправьте семантику в app-header, вместо `span` должны быть ссылки `a`.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/app-header/app-header.jsx
> +                </span>
**Надо исправить**

Оберните иконку и текст в ссылку в шапке в ссылку `<a href="#">`

Например
```js
<a href="#" class="......">
   <BurgerIcon type="primary" /> Конструктор
</a>
```
В следующих спринтах вместо ссылки будет компонент Link из библиотеки react router, а пока сделайте просто ссылкой

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +    }
**Надо исправить:** Это лучше сделать просто переменной, а не функцией. Также лучше обернуть в `useMemo`.

```js
const bun = props.ingredients.find(x => x.type === "bun");
```

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +    const renderBun = (bun, type, extraClass) => {
**Надо исправить:** Здесь и во всех похожих местах. Рендер лучше делать напрямую в `jsx`.

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +                text={bun.name}
**Надо исправить:** Булки должны иметь приписки: `верх` и `низ`;

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +            {(bun !== undefined) && renderBun(bun, "top", "mb-4")}
**Можно лучше:** Лучше написать так: 

```js
{bun && /** ... */}
```

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +                    (ingredient.type !== "bun") && renderIngredient(ingredient)
**Надо исправить:** Тут лучше выполнить фильтрацию до jsx: 

```js
const ingredients = data.filter(ingredient => ingredient.type!=='bun');
```

И еще обернуть это в useMemo.

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +                <Price large={true} price={props.ingredients.reduce((sum, element) => sum + element.price, 0)}/>
**Надо исправить:** Расчёт стоимости нужно вынести в переменную, и обернуть в `useMemo`.

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +    ingredients: PropTypes.arrayOf(PropTypes.shape({
**Надо исправить:**
Исправьте во всём проекте.
Необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes.
Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
```

**Можно лучше:**

Во многих компонентах дублируется описание PropTypes ингредиента.

Лучше вынести его в отдельный файл (можно создать файл prop-types.js в корне src) и переиспользовать описание пропсов ингрединта, а не дублировать.

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    const sauceIngredients = props.ingredients.filter(x => x.type === "sauce");
**Можно лучше:** Оберните в useMemo.

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                <Tab value="buns" active={current==="buns"} onClick={() => executeScroll(bunRef, "buns")}>Булки</Tab>
**Можно лучше:** 
Здесь и далее.
Лучше написать так, внимательно посмотрите что из себя представляет пропс `onClick`.

```js
  <Tab value="buns" active={current==="buns"} onClick={(value) => executeScroll(bunRef, value)}>{/** ... */}</Tab>
```

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/constructor/constructor.jsx
> +        if (ingredient.type === "bun" && selectedIngredients.find(x => x.type === "bun")) {
**надо исправить:** Пустых условий быть не должно, измените его.

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/constructor/constructor.jsx
> +    const url = "https://norma.nomoreparties.space/api/ingredients";
**Надо исправить:**

Вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/constructor/constructor.jsx
> +            .then(res => res.json())
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```js
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответит не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```js
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/constructor/constructor.jsx
> +                setIsLoaded(true);
**Можно лучше:**

Вызывать скрытие индикатора загрузки слудеует в блоке `finally`, а не дублировать в `then` и `catch`
[https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally)

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/constructor/constructor.jsx
> +    const getUniqId = () => {
**Надо исправить:** Вынесите функцию в отдельный файл, в папку utils.

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +        document.getElementById("modals")
**можно лучше:** Лучше вынести в переменную, и за пределы компонента.

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/constructor/constructor.jsx
> +            {modal.isVisible && <Modal children={modal.content} setModal={setModal}/>}
**Надо исправить:** children нужно передавать не как пропс, а как компонент внутри компонента. 

```js
<Modal setModal={setModal}>
  {modal.content}
</Modal>
```

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/ingredient-details/ingredient-details.jsx
> +				<img src={props.ingredient.image_large}/>
**Надо исправить:** Элемент `img`, должен иметь атрибут `alt`.

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/ingredients-list/ingredients-list.jsx
> +                        count={props.selectedIngredients.filter(x => x._id === ingredient._id).length}
**Можно лучше:** Лучше считать до `jsx`. Для этого создайте объект в котором в качестве ключей будут `_id` ингредиентов, а в качестве значений, количество.

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +        if (e.keyCode === 27) {
**Надо исправить**

вынесите магическое значение 27 в именованную константу `const ECK_KEYCODE = 27`

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +    }
**Можно лучше:** Лучше занести в useEffect.

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +    React.useEffect(() => {
**надо исправить:** вам нужно указать пустой массив зависимостей у useEffect, иначе подписчики событий будут срабатывать каждый раз при ререндере.

2022-11-05 06:47 UTC, ArslanDev666 commented on src/components/price/price.jsx
> +Price.propTypes = {
**надо исправить:** описаны не все propTypes для пропсов, который используются в компоненте.

2022-11-06 16:54 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Практически все замечания с прошлого ревью были исправлены.**

### **Но есть несколько замечаний, которые нужно исправить:**

- Поправьте цвет фона у app-header.

  Как у вас: https://yadi.sk/d/M-ucqK9uoREzvA;
  Как в макете: https://yadi.sk/d/VKN8hQCh9VkrVA;

- Поправьте вёрстку модального окна с заказом.

  Как у вас: https://yadi.sk/d/cdyoAtSEeYGTfw;
  Как в макете: https://yadi.sk/d/OH0ssw77ccf4XQ;

- Поправить расчёт стоимости.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-11-06 16:54 UTC, ArslanDev666 commented on src/components/constructor/constructor.jsx
> +            })
**Надо исправить:** Тут лучше использовать метод map. 

```js
// Где-то за пределами компонента.

const BURGER_CONSTRUCTOR_INGREDIENTS_INDEXES = [0, 8, 3, 4, 6, 7, 7];

//  constructor.js

const burgerConstructorIngredients = BURGER_CONSTRUCTOR_INGREDIENTS_INDEXES.map((index) => ({
  ...result.data[index],
  uniqId: getUniqId(),
}));
setSelectedIngredients(burgerConstructorIngredients);
```

Лучше конечно, вообще сейчас не думать об этом, но если уж взялись, то нужно делать хорошо.
По хорошему бы ещё делать проверку на то, что есть ли вообще такой индекс, а также вообще уйти от индексов к _id, но чего нет, того нет)

2022-11-06 16:54 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +            return props.ingredients.reduce((sum, element) => sum + element.price, 0)
**Надо исправить:** 

В расчёте стоимости, вы не учитываете что булки у нас 2 шт, а не 1.

2022-11-06 16:58 UTC, Fighter9021 commented on src/components/burger-constructor/burger-constructor.jsx
> +            return props.ingredients.reduce((sum, element) => sum + element.price, 0)
Я наоборот осознанно полагал, что как одна считаются. Странно платить за каждую булку отдельно)

2022-11-07 04:51 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +            return props.ingredients.reduce((sum, element) => sum + element.price, 0)
Понимаю :) но к сожалению, такое вот условие, вроде бы нигде об этом не написано, но оно есть.

2022-11-07 15:16 UTC, merged